#!/bin/sh

youtube=(
	# Invidious
	"yewtu.be"
	"invidious.osi.kr"
	"invidious.flokinet.to"
	"inv.riverside.rocks"
	"yt.artemislena.eu"
	"invidio.xamh.de"
	"vid.puffyan.us"
	"invidious-us.kavin.rocks"
	"invidious.esmailelbob.xyz"
	"invidious.snopyta.org"
	"invidious.weblibre.org"
	"invidious.namazso.eu"
	"youtube.076.ne.jp"
	"invidious.mutahar.rocks"
	"invidious.privacy.gd"
	"inv.bp.mutahar.rocks"
	"tube.cthd.icu"
	"invidious.lunar.icu"

	# Piped
	"piped.kavin.rocks"
	"piped.silkky.cloud"
	"piped.tokhmi.xyz"
	"il.ax"
	"piped.syncpundit.com"
	"piped.mint.lgbt"
	"piped.notyourcomputer.net"
)

twitter=(
	# Nitter
	"nitter.net"
	"nitter.42l.fr"
	"nitter.pussthecat.org"
	"nitter.kavin.rocks"
	"nitter.unixfox.eu"
	"nitter.unixfox.eu"
	"nitter.eu"
	"nitter.namazso.eu"
	"nitter.actionsack.com"
	"nitter.hu"
	"nitter.moomoo.me"
	"nittereu.moomoo.me"
	"nitter.it"
	"nitter.grimneko.de"
	"nitter.sethforprivacy.com"
	"nttr.stream"
	"nitter.cutelab.space"
	"nitter.mint.lgbt"
	"nitter.bus-hit.me"
	"nitter.datatunnel.xyz"
	"nitter.esmailelbob.xyz"
	"tw.artemislena.eu"
	"de.nttr.stream"
	"nitter.winscloud.net"
	"nitter.tiekoetter.com"
	"nitter.spaceint.fr"
	"twtr.bch.bar"
	"nitter.privacy.com.de"
	"nitter.mastodon.pro"
	"nitter.notraxx.ch"
	"nitter.poast.org"
	"nitter.lunar.icu"
	"nitter.bird.froth.zone"
)

instagram=(
	# Bibliogram
	"bibliogram.art"
	"bibliogram.snopyta.org"
	"bibliogram.pussthecat.org"
	"bibliogram.1d4.us"
	"insta.trom.tf"
	"bib.actionsack.com"
	"biblio.alefvanoon.xyz"
)

tiktok=(
	# ProxiTok
	"proxitok.herokuapp.com"
)

reddit=(
	# teddit
	"teddit.net"
	"teddit.ggc-project.de"
	"teddit.zaggy.nl"
	"teddit.namazso.eu"
	"teddit.alefvanoon.xyz"
	"incogsnoo.com"
	"teddit.pussthecat.org"
	"reddit.lol"
	"teddit.sethforprivacy.com"
	"teddit.totaldarkness.net"
	"teddit.adminforge.de"
	"teddit.bus-hit.me"
	"teddit.froth.zone"
	"rdt.trom.tf"

	# libreddit
	"libredd.it"
	"libreddit.spike.codes"
	"libreddit.dothq.co"
	"libreddit.kavin.rocks"
	"reddit.invak.id"
	"lr.riverside.rocks"
	"libreddit.silkky.cloud"
	"libreddit.privacy.com.de"
	"libreddit.domain.glass"
	"reddit.artemislena.eu"
	"r.nf"
	"libreddit.some-things.org"
	"reddit.stuehieyr.com"
	"lr.mint.lgbt"
	"libreddit.alefvanoon.xyz"
	"libreddit.igna.rocks"
	"libreddit.autarkic.org"
	"libreddit.drivet.xyz"
	"libreddit.de"
	"libreddit.pussthecat.org"
	"libreddit.mutahar.rocks"
	"libreddit.northboot.xyz"
	"leddit.xyz"
	"de.leddit.xyz"
	"lr.cowfee.moe"
	"libreddit.hu"
	"libreddit.totaldarkness.net"
	"libreddit.esmailelbob.xyz"
	"libreddit.nl"
	"lr.stilic.ml"
	"reddi.tk"
	"libreddit.bus-hit.me"
	"libreddit.datatunnel.xyz"
	"r.walkx.org"
	"libreddit.kylrth.com"
	"libreddit.yonalee.eu"
	"libreddit.tiekoetter.com"
	"reddit.rtrace.io"
	"libreddit.lunar.icu"
)

link="$1"
if [[ "$1" =~ "youtube.com" || "$1" =~ "youtu.be" ]]; then
	instance="${youtube[$(($RANDOM % ${#youtube[@]}))]}"
	link=$(echo "$1" | sed "s/www\.youtube\.com/$instance/")
	link=$(echo "$link" | sed "s/youtu\.be\//$instance\/watch?v=/")
elif [[ "$1" =~ "twitter.com" ]]; then
	instance="${twitter[$(($RANDOM % ${#twitter[@]}))]}"
	link=$(echo "$1" | sed "s/twitter\.com/$instance/")
elif [[ "$1" =~ "instagram.com" ]]; then
	instance="${instagram[$(($RANDOM % ${#instagram[@]}))]}"
	link=$(echo "$1" | sed "s/\.com\/\(\w\{2,\}\)/.com\/u\/\1/" )
	link=$(echo "$link" | sed "s/www\.instagram\.com/$instance/")
elif [[ "$1" =~ "tiktok.com" ]]; then
	instance="${tiktok[$(($RANDOM % ${#tiktok[@]}))]}"
	link=$(echo "$link" | sed "s/www\.tiktok\.com/$instance/")
	# TODO: Also check for other link formats
elif [[ "$1" =~ "reddit.com" ]]; then
	instance="${reddit[$(($RANDOM % ${#reddit[@]}))]}"
	link=$(echo "$link" | sed "s/www\.reddit\.com/$instance/")
fi

[ "$1" != "$link" ] && xdg-open "$link" >/dev/null